### PR TITLE
Update cd-dc.phac-aspc.alpha.canada.ca.yaml

### PR DESCRIPTION
**Pull request by gagandeepsingh1105**
Migrated to new GCP project

### CODE REVIEW

**Comment by tcaky** [comment]
@gagandeepsingh1105 We are closing down the alpha.canada DNS service.  Please migrate all existing to a new endpoint on the new service at: https://github.com/PHACDataHub/phac-dns/

**Comment by vedantthapa** [comment]
Hey @tcaky, we've migrated over to phac-dns (See https://github.com/PHACDataHub/phac-dns/pull/94). This one is required because the client (@AlexCLeduc) has redirects set up from cd-dc / dc-cd to the new endpoint (catalogue.alpha.phac-aspc.gc.ca) since they'd like to migrate incrementally to the new domain.

**Comment by vedantthapa** [comment]
Hey @tcaky, we've migrated over to phac-dns (See https://github.com/PHACDataHub/phac-dns/pull/94). This one is required because the client (@AlexCLeduc) has redirects set up from cd-dc / dc-cd to the new endpoint (catalogue.alpha.phac-aspc.gc.ca) since they'd like to migrate incrementally to the new domain.

**Review by tcaky — APPROVED** [review]
LGTM

**Pull request merged**
